conversation:
  initiate:
    agent_phone_number: "+916260461864" # Phone number the bot will transfer the call to if customer asks for a human agent
    bot_company: More Telecom
    bot_name: Noah
    lang: {}

communication_services:
  phone_number: "+18882806107" # Phone number purshased from  Communication Services

sms: {}

prompts:
  llm: {}
  tts: {}
